// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-orders.ts
var list_orders_default = defineTool({
  name: "list_orders",
  title: "Listar ordens de servi\xE7o",
  description: "Lista as ordens de servi\xE7o (OS) da assist\xEAncia t\xE9cnica do usu\xE1rio autenticado, com filtro opcional por status e busca por equipamento ou n\xFAmero da OS.",
  inputSchema: {
    status: z.string().optional().describe("Filtra por status da OS, por exemplo: aberta, em_andamento, concluida, cancelada."),
    search: z.string().optional().describe("Busca por n\xFAmero da OS, equipamento ou defeito relatado."),
    limit: z.number().int().optional().describe("M\xE1ximo de ordens retornadas (padr\xE3o 20, m\xE1ximo 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, os_number, device, issue, status, priority, category, total_sale, total_cost, total_profit, created_at, completed_at, clients(name, phone)"
    ).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`os_number.ilike.%${search}%,device.ilike.%${search}%,issue.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_order_default = defineTool2({
  name: "get_order",
  title: "Detalhar ordem de servi\xE7o",
  description: "Retorna os detalhes completos de uma ordem de servi\xE7o (dados do equipamento, cliente e itens de reparo) pelo n\xFAmero da OS ou pelo id.",
  inputSchema: {
    os_number: z2.string().optional().describe("N\xFAmero da OS, por exemplo OS-0012-2026."),
    id: z2.string().optional().describe("Identificador (uuid) da ordem de servi\xE7o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ os_number, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    if (!os_number && !id) {
      return { content: [{ type: "text", text: "Informe os_number ou id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, os_number, device, issue, status, priority, category, serial_number, accessories, internal_notes, total_sale, total_cost, total_profit, created_at, completed_at, clients(id, name, phone, email), order_items(*)"
    ).limit(1);
    query = id ? query.eq("id", id) : query.eq("os_number", os_number);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Ordem de servi\xE7o n\xE3o encontrada." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista os clientes cadastrados do usu\xE1rio autenticado, com busca opcional por nome, telefone, e-mail, CPF ou CNPJ.",
  inputSchema: {
    search: z3.string().optional().describe("Texto para buscar por nome, telefone ou e-mail do cliente."),
    limit: z3.number().int().optional().describe("M\xE1ximo de clientes retornados (padr\xE3o 20, m\xE1ximo 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, name, phone, email, client_type, cpf, cnpj, city, state, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (search) query = query.or(`name.ilike.%${search}%,phone.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_client_default = defineTool4({
  name: "create_client",
  title: "Cadastrar cliente",
  description: "Cadastra um novo cliente na assist\xEAncia t\xE9cnica do usu\xE1rio autenticado.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Nome completo ou raz\xE3o social do cliente."),
    phone: z4.string().optional().describe("Telefone/WhatsApp do cliente."),
    email: z4.string().optional().describe("E-mail do cliente."),
    client_type: z4.string().optional().describe("Tipo do cliente: 'pf' (pessoa f\xEDsica) ou 'pj' (pessoa jur\xEDdica)."),
    cpf: z4.string().optional().describe("CPF, quando pessoa f\xEDsica."),
    cnpj: z4.string().optional().describe("CNPJ, quando pessoa jur\xEDdica."),
    notes: z4.string().optional().describe("Observa\xE7\xF5es internas sobre o cliente.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clients").insert({ ...input, user_id: ctx.getUserId() }).select("id, name, phone, email, client_type").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Cliente criado: ${JSON.stringify(data)}` }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/tools/list-inventory.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_inventory_default = defineTool5({
  name: "list_inventory",
  title: "Consultar estoque",
  description: "Lista os produtos/pe\xE7as do estoque do usu\xE1rio autenticado, com op\xE7\xE3o de mostrar apenas itens com estoque baixo (abaixo do m\xEDnimo).",
  inputSchema: {
    search: z5.string().optional().describe("Busca por nome ou SKU do produto."),
    low_stock_only: z5.boolean().optional().describe("Se verdadeiro, retorna apenas itens com estoque igual ou abaixo do m\xEDnimo."),
    limit: z5.number().int().optional().describe("M\xE1ximo de produtos retornados (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, low_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, name, sku, category, stock, min_stock, cost_price, sale_price").order("name", { ascending: true }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) query = query.or(`name.ilike.%${search}%,sku.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter((p) => low_stock_only ? Number(p.stock) <= Number(p.min_stock) : true);
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { products: rows }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool6({
  name: "financial_summary",
  title: "Resumo financeiro",
  description: "Resume receitas, despesas, custos e lucro das transa\xE7\xF5es financeiras do usu\xE1rio autenticado em um per\xEDodo (datas ISO YYYY-MM-DD).",
  inputSchema: {
    start_date: z6.string().optional().describe("Data inicial no formato YYYY-MM-DD."),
    end_date: z6.string().optional().describe("Data final no formato YYYY-MM-DD."),
    status: z6.string().optional().describe("Filtra por status da transa\xE7\xE3o, por exemplo 'pago' ou 'pendente'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("financial_transactions").select("type, amount, cost_amount, profit_amount, status, created_at").limit(5e3);
    if (start_date) query = query.gte("created_at", `${start_date}T00:00:00Z`);
    if (end_date) query = query.lte("created_at", `${end_date}T23:59:59Z`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const sum = (pred, key) => rows.filter(pred).reduce((acc, r) => acc + Number(r[key] ?? 0), 0);
    const summary = {
      transactions: rows.length,
      revenue: sum((r) => r.type === "receita", "amount"),
      expenses: sum((r) => r.type === "despesa", "amount"),
      costs: sum(() => true, "cost_amount"),
      profit: sum(() => true, "profit_amount"),
      period: { start_date: start_date ?? null, end_date: end_date ?? null }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cahkipreywowzjenpovw";
var mcp_default = defineMcp({
  name: "techcare-os",
  title: "TechCare OS",
  version: "0.1.0",
  instructions: "Ferramentas do TechCare OS, sistema de gest\xE3o para assist\xEAncias t\xE9cnicas. Use list_orders e get_order para consultar ordens de servi\xE7o, list_clients e create_client para clientes, list_inventory para estoque e pe\xE7as, e financial_summary para receitas, despesas e lucro em um per\xEDodo. Todas as opera\xE7\xF5es s\xE3o feitas na conta do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_orders_default, get_order_default, list_clients_default, create_client_default, list_inventory_default, financial_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
